groups:
- color: '#4CAF50'
  id: 1
  name: Разработчики
- color: '#FF9800'
  id: 2
  name: Тестировщики
- color: '#00BCD4'
  id: 3
  name: Автотестировщики
- color: '#9C27B0'
  id: 4
  name: Аналитики
- color: '#795548'
  id: 5
  name: Технические писатели
- color: '#F44336'
  id: 6
  name: Менеджеры
jira:
  origin: https://oneproject.it-one.ru
  url: https://oneproject.it-one.ru/jira/secure/RapidBoard.jspa?rapidView=327
users:
- groups: []
  name: Margarita
  patronymic: ''
  status: Активен
  surname: Zhivotovskaya
- groups: []
  name: Valeriy
  patronymic: ''
  status: Активен
  surname: Sukhorukov
- groups: []
  name: Elizaveta
  patronymic: ''
  status: Активен
  surname: Starovoitova
- groups: []
  name: Andrey
  patronymic: ''
  status: Активен
  surname: Shapovalov
- groups: []
  name: Alexander
  patronymic: ''
  status: Активен
  surname: Petrenko
- groups: []
  name: Kseniya
  patronymic: ''
  status: Активен
  surname: Ostanina
- groups: []
  name: Polina
  patronymic: ''
  status: Активен
  surname: Ognegina
- groups: []
  name: Igor
  patronymic: ''
  status: Активен
  surname: Nedomolkin
- groups: []
  name: Dariya
  patronymic: ''
  status: Активен
  surname: Markina
- groups: []
  name: Sergey
  patronymic: ''
  status: Активен
  surname: Lukayanov
- groups: []
  name: Rinat
  patronymic: ''
  status: Активен
  surname: Khalibulov
- groups:
  - 3
  name: Aleksei
  patronymic: ''
  status: Активен
  surname: Korolkov
- groups:
  - 3
  name: Alina
  patronymic: ''
  status: Активен
  surname: Kobzar
- groups: []
  name: Rustam
  patronymic: ''
  status: Активен
  surname: Karsakov
- groups: []
  name: Rauf
  patronymic: ''
  status: Активен
  surname: Gasanov
- groups: []
  name: Aleksandr
  patronymic: ''
  status: Активен
  surname: Garibov
- groups: []
  name: Anastasiya
  patronymic: ''
  status: Активен
  surname: Fedoseeva
- groups: []
  name: Julia
  patronymic: ''
  status: Активен
  surname: Ababina
- groups: []
  name: Julia
  patronymic: ''
  status: Активен
  surname: Zvereva
- groups: []
  name: Sergey
  patronymic: ''
  status: Активен
  surname: Korotkiy
- groups: []
  name: Anton
  patronymic: ''
  status: Активен
  surname: Schastnyi
- groups: []
  name: Ivan
  patronymic: ''
  status: Активен
  surname: Nomokonov
- groups: []
  name: Anna
  patronymic: ''
  status: Активен
  surname: Kogan
- groups: []
  name: Margarita
  patronymic: ''
  status: Активен
  surname: Zhivotovskaya
- groups: []
  name: Alexey
  patronymic: ''
  status: Активен
  surname: Vasiliev
- groups: []
  name: Alexander
  patronymic: ''
  status: Активен
  surname: Petrenko
- groups: []
  name: Valeriy
  patronymic: ''
  status: Активен
  surname: Sukhorukov
- groups: []
  name: Kseniya
  patronymic: ''
  status: Активен
  surname: Ostanina
- groups:
  - 3
  name: Dariya
  patronymic: ''
  status: Активен
  surname: Markina
- groups: []
  name: Alexey
  patronymic: ''
  status: Активен
  surname: Vasiliev
